baseURL = "https://vivekr.dev"
languageCode = "en-us"
title = "Vivek R"
theme = "ezhil"
paginate = 7

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-19841405-18"
disqusShortname = "vivekrdev"

[params]
	subtitle = "Full Stack Developer, building fintech tools [@zerodha](https://zerodha.com)"
	mainSections = ["posts"]
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	mode = "auto"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Projects"
url = "https://github.com/vividvilla?utf8=%E2%9C%93&tab=repositories&q=&type=source"
weight = 5

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/vividvilla"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/vividvilla"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
tag = "tags"
